server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coupang
    username: yujeonmu
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

logging:
  level:
    root: info
    me.hong.kotlinspring: debug
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 7
